Lorenz ODE as example
ornladios/ADIOS2-Examples pull request #29
Opened 2020-04-08 13:41 UTC by NAThompson

This example is in response to a conversation we have on teams with @pnorbert .

The example solves the [Lorenz system](https://en.wikipedia.org/wiki/Lorenz_system) via an adaptive Taylor method. It presents a few challenges for ADIOS: First, the number of state points in the state vector varies wildly. Second, the natural datastructure is an array of structs.

The code validates that the array of structs has contiguous layout, as there is nothing [guaranteed by the standard](https://stackoverflow.com/questions/54197195/what-is-the-memory-layout-of-vector-of-arrays). Then it pipes variable-sized data to independent variables, which, though inelegant, is what I understand to be required. (Is there a more elegant way to do it?)

Finally, once I get a little feedback, I'll bring in MPI, and we can really fill up the phase space with trajectories; which should be a very useful simplified model for particle advection.

2020-04-08 23:15 UTC, williamfgc requested changes
@NAThompson overall this is great. Since this is used for tutorials and newcomers, I'd recommend using `const` whenever possible since it improves tremendously code readability (and compile-time safety).

2020-04-08 23:15 UTC, williamfgc commented on source/cpp/lorenz_ode/lorenz_writer.cpp
> +                std::string variable = "u" + std::to_string(i) + std::to_string(j) + std::to_string(k);
add `const`

2020-04-08 23:15 UTC, williamfgc commented on source/cpp/lorenz_ode/lorenz_writer.cpp
> +                std::array<Real, 3> initial_conditions{Real(i),Real(j),Real(k)};
`const`?

2020-04-08 23:15 UTC, williamfgc commented on source/cpp/lorenz_ode/lorenz.hpp
> +        Real x = initial_conditions[0];
`const`

2020-04-08 23:16 UTC, williamfgc commented
Also, please rebase `master`. Github is showing an out-of-date issue.

2020-04-09 12:01 UTC, NAThompson commented on source/cpp/lorenz_ode/lorenz_writer.cpp
> +                std::array<Real, 3> initial_conditions{Real(i),Real(j),Real(k)};
Fixed.

2020-04-09 12:01 UTC, NAThompson commented on source/cpp/lorenz_ode/lorenz_writer.cpp
> +                std::string variable = "u" + std::to_string(i) + std::to_string(j) + std::to_string(k);
Fixed.

2020-04-09 12:17 UTC, williamfgc commented
@NAThompson great, thanks!

2020-04-09 12:17 UTC, merged

2020-04-09 12:21 UTC, NAThompson commented
@williamfgc : Thanks so much for being so helpful here; I hope you won't find it frustrating that I'm going to put in a PR for a reader as well!

(I should've marked the PR as a draft; my bad. But it appears github doesn't allow you to retroactively mark a PR as a draft after opening it.)

2020-04-09 13:00 UTC, williamfgc commented
Happy to help and thanks for adding examples. We don't know where users come from and having examples that relate to their tasks helps a lot.